-- Migration: Create whatsapp_integracao table and policies
-- Date: 2026-08-18 09:06:00

-- Create whatsapp_integracao table
CREATE TABLE IF NOT EXISTS public.whatsapp_integracao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  whatsapp_number TEXT,
  instance_name TEXT,
  server_url TEXT,
  token_secret_id UUID REFERENCES vault.secrets(id) ON DELETE SET NULL,
  ativo BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- Index to enforce Rule: Only 1 active WhatsApp integration per user at a time
CREATE UNIQUE INDEX IF NOT EXISTS unique_active_whatsapp_integration_per_user 
  ON public.whatsapp_integracao (user_id) 
  WHERE (ativo = true);

-- Enable RLS
ALTER TABLE public.whatsapp_integracao ENABLE ROW LEVEL SECURITY;

-- Drop policy if exists to avoid conflicts
DROP POLICY IF EXISTS "Whatsapp integracao isolation select policy" ON public.whatsapp_integracao;

-- Select policy to isolate access to the row owner
CREATE POLICY "Whatsapp integracao isolation select policy" ON public.whatsapp_integracao
  FOR SELECT
  USING (
    auth.uid() = user_id
  );
